@baseUrl = http://localhost:3333

# @name list_plants
GET {{baseUrl}}
Content-Type: application/json

###

# @name create_plant
POST {{baseUrl}}
Content-Type: application/json

{
  "careInstructions": [
    "New example careInstructions 1",
    "New example careInstructions 2",
		"New example careInstructions 3"
  ],
	"description": "New example description",
	"imageUrl": "New example image url",
	"name": "New example name",
	"type": "New example type"
}